# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FactsTask' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


 pod 'SwiftyJSON'

  # Pods for FactsTask

  target 'FactsTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FactsTaskUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
